'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const data=require('../assets/word-data.js');const {M}=require('./helpers/grouped-fixtures.cjs');
const {validateCatalogFiles}=require('../config/validate-words.cjs');
const catalog=()=>[{id:'w_000001',english:'penetrate',meanings:M('穿透；滲透'),lessonIds:['U6']},{id:'w_000002',english:'record',meanings:[...M('紀錄',['noun']),...M('記錄；錄製')],lessonIds:['U8']}];
const model=(state={})=>data.createUserWordState(catalog(),state);
test('expanded catalog retains all 892 historical identity mappings and frozen backups',()=>{assert.deepEqual(validateCatalogFiles(),{words:452,memberships:478,aliases:17,legacyIds:446,mappedIds:892,lessonFiles:9,frozenFiles:14});});
test('U2 imports 32 spellings with shared identities and retains all existing course memberships',()=>{
 const words=require('../data/words.json'), before=require('../migration/schema-v5-catalog.json');
 const shared={antique:'w_000157',applause:'w_000081',apt:'w_000060',asset:'w_000108',attendance:'w_000148',ballot:'w_000142',barren:'w_000322',batch:'w_000323',behalf:'w_000017'};
 const newNames=['analyst','anonymous','antarctic','appliance','arctic','armor','arouse','array','arrogant','artery','articulate','artifact','assert','attic','attorney','attribute','auction','authorize','autonomy','availability','bandit','barefoot','bazaar'];
 const u2=words.filter(w=>w.lessonIds.includes('死神單字Lv5U2'));
 assert.deepEqual(u2.map(w=>w.english).sort(),[...Object.keys(shared),...newNames].sort());
 for(const old of before){
  const word=words.find(w=>w.id===old.id);assert.equal(word.english,old.english);
  assert.deepEqual(word.lessonIds,[...old.lessonIds,...(Object.hasOwn(shared,old.english)?['死神單字Lv5U2']:[])]);
  assert.equal(word.isWrong,old.isWrong);
 }
 for(const [english,id] of Object.entries(shared))assert.equal(u2.find(w=>w.english===english).id,id);
 newNames.forEach((english,index)=>assert.equal(u2.find(w=>w.english===english).id,`w_${String(430+index).padStart(6,'0')}`));
 assert.equal(words.filter(w=>w.lessonIds.includes('死神單字Lv5 a')).length,40);
 assert.deepEqual(u2.find(w=>w.english==='batch').meanings,[...M('一批；一組',['noun']),...M('分批')]);
 assert.deepEqual(u2.find(w=>w.english==='auction').meanings,M('拍賣',['noun','verb']));
 assert.deepEqual(u2.find(w=>w.english==='arctic').meanings,[...M('北極',['noun']),...M('北極的',['adjective'])]);
 assert.deepEqual(u2.find(w=>w.english==='antarctic').meanings,[...M('南極',['noun']),...M('南極的',['adjective'])]);
});
test('registered public lessons exist before import and a renamed title retains its identity',()=>{
 assert.deepEqual(data.getPublicLessonIds([]),['死神單字Lv5 a','死神單字Lv5U2']);
 assert.equal(data.getPublicLessonName('死神單字Lv5 a'),'死神單字Lv5U1');
 assert.equal(data.getPublicLessonName('晟景Lv5U6'),'晟景Lv5U6');
 assert.equal(data.getPublicLessonName('constructor'),'constructor');
 const ids=data.getPublicLessonIds([{lessonIds:['死神單字Lv5 a','晟景Lv5U6']}]);ids.push('rogue');
 assert.deepEqual(data.getPublicLessonIds([]),['死神單字Lv5 a','死神單字Lv5U2']);
});
test('opaque identity survives English, grouped meanings and lesson edits',()=>{const m=model();m.updateWordOverride('w_000001',{english:'changed',meanings:M('個人')});m.setWordLessons('w_000001',['U8']);assert.equal(m.getEffectiveWord('w_000001').id,'w_000001');assert.equal(data.normalizeCatalog([{...catalog()[0],english:'other',lessonIds:[]}])[0].id,'w_000001');assert.throws(()=>data.normalizeCatalog([{...catalog()[0],id:'U6::penetrate'}]),/ID/);});
test('canonical catalog forbids duplicate case-insensitive English and standalone meaning/POS',()=>{assert.throws(()=>data.normalizeCatalog([...catalog(),{...catalog()[0],id:'w_000003',english:'PENETRATE'}]),/Duplicate/);assert.throws(()=>data.normalizeCatalog([...catalog(),catalog()[0]]),/Duplicate/);for(const field of ['meaning','partOfSpeech','tags','folderId','folderIds','source','defaultId'])assert.throws(()=>data.normalizeCatalog([{...catalog()[0],[field]:[]}]),/Unknown/);});
test('noun and verb have separate definitions inside one word entity',()=>{const m=model(),w=m.getEffectiveWord('w_000002');assert.equal(m.deriveEffectiveWords().length,2);assert.deepEqual(w.meanings,[...M('紀錄',['noun']),...M('記錄；錄製')]);assert.equal(Object.hasOwn(w,'partOfSpeech'),false);assert.equal(Object.hasOwn(w,'meaning'),false);});
test('group validation rejects duplicates and malformed definitions; normalizes order without sharing references',()=>{assert.throws(()=>data.normalizeMeanings([...M('一'),...M('二')]),/Duplicate/);assert.throws(()=>data.normalizeMeanings([{partOfSpeech:'noun',definitions:'錯誤'}]),/array/);assert.throws(()=>data.normalizeMeanings([{partOfSpeech:'invalid',definitions:[]}]),/Unknown/);assert.deepEqual(data.normalizeMeanings([...M('動'),...M('名',['noun'])]),[...M('名',['noun']),...M('動')]);});
test('A and B personal grouped meanings cannot mutate each other or public catalog',()=>{const base=catalog(),original=JSON.stringify(base),a=data.createUserWordState(base),b=data.createUserWordState(base),visitor=data.createUserWordState(base);a.updateWordOverride('w_000001',{meanings:M('A')});b.updateWordOverride('w_000001',{meanings:M('B')});assert.deepEqual(a.getEffectiveWord('w_000001').meanings,M('A'));assert.deepEqual(b.getEffectiveWord('w_000001').meanings,M('B'));assert.deepEqual(visitor.getEffectiveWord('w_000001').meanings,M('穿透；滲透'));a.getEffectiveWord('w_000001').meanings[0].definitions.push('rogue');assert.deepEqual(a.getWordOverride('w_000001').meanings,M('A'));assert.equal(JSON.stringify(base),original);});
test('only grouped differences are stored; restoring equality removes the empty override',()=>{const m=model();m.updateWordOverride('w_000001',{meanings:M('私人')});assert.deepEqual(m.exportState().userOverrides,{w_000001:{meanings:M('私人')}});m.updateWordOverride('w_000001',{meanings:M('穿透；滲透')});assert.deepEqual(m.exportState().userOverrides,{});});
test('empty groups and false are explicit personal values; clearing meanings inherits latest public',()=>{const m=data.createUserWordState([{...catalog()[0],isWrong:true}]);m.updateWordOverride('w_000001',{meanings:[],isWrong:false});m.setPublicCatalog([{...catalog()[0],meanings:M('新版'),isWrong:true}]);assert.deepEqual(m.getEffectiveWord('w_000001').meanings,[]);m.clearWordOverrideField('w_000001','meanings');assert.deepEqual(m.getEffectiveWord('w_000001').meanings,M('新版'));assert.deepEqual(m.getWordOverride('w_000001'),{isWrong:false});});
test('public group updates inherit unless personally overridden and restore follows latest base',()=>{const a=model(),b=model();a.updateWordOverride('w_000001',{meanings:M('custom')});const next=catalog();next[0].meanings=M('v2');a.setPublicCatalog(next);b.setPublicCatalog(next);assert.deepEqual(a.getEffectiveWord('w_000001').meanings,M('custom'));assert.deepEqual(b.getEffectiveWord('w_000001').meanings,M('v2'));a.clearWordOverride('w_000001');assert.deepEqual(a.getEffectiveWord('w_000001').meanings,M('v2'));});
test('unrelated updates preserve explicit meanings even when public catches up',()=>{const m=model({userOverrides:{w_000001:{meanings:M('穿透；滲透'),removedLessonIds:['future']}}});m.updateWordOverride('w_000001',{isWrong:true});m.setWordFolders('w_000001',['f']);assert.deepEqual(m.getWordOverride('w_000001').meanings,M('穿透；滲透'));assert.deepEqual(m.getWordOverride('w_000001').removedLessonIds,['future']);});
test('lesson deltas remain separate from same-named private folders and other accounts',()=>{const a=model({userOverrides:{w_000001:{addedLessonIds:['U8'],removedLessonIds:['U6'],folderIds:['U6']}}});assert.deepEqual(a.getEffectiveWord('w_000001').lessonIds,['U8']);assert.deepEqual(a.getEffectiveWord('w_000001').folderIds,['U6']);assert.deepEqual(model().getEffectiveWord('w_000001').lessonIds,['U6']);a.setWordLessons('w_000001',[]);a.clearLessonChange('w_000001','U6');assert.deepEqual(a.getEffectiveWord('w_000001').lessonIds,['U6']);});
test('dormant lesson removals survive future public changes',()=>{const m=model({userOverrides:{w_000001:{removedLessonIds:['future']}}});m.setWordLessons('w_000001',['U6','extra']);const next=catalog();next[0].lessonIds=['U6','future','new'];m.setPublicCatalog(next);assert.deepEqual(m.getEffectiveWord('w_000001').lessonIds,['U6','new','extra']);});
test('hide/restore retain meanings and custom deletion never deletes public words',()=>{const m=model();m.updateWordOverride('w_000001',{meanings:M('mine')});m.hidePublicWord('w_000001');assert.equal(m.deriveEffectiveWords().length,1);m.restorePublicWord('w_000001');assert.deepEqual(m.getEffectiveWord('w_000001').meanings,M('mine'));m.createCustomWord('c',{english:'custom',meanings:M('mine',['noun'])});m.deleteCustomWord('c');assert.equal(m.deriveEffectiveWords().length,2);assert.throws(()=>m.deleteCustomWord('w_000001'),/Reserved/);});
test('new and renamed English cannot collide including hidden words',()=>{const m=model();m.hidePublicWord('w_000001');assert.throws(()=>m.createCustomWord('c',{english:'PENETRATE'}),/Duplicate/);m.createCustomWord('c',{english:'mine'});assert.throws(()=>m.updateCustomWord('c',{english:'Record'}),/Duplicate/);assert.throws(()=>m.updateWordOverride('w_000002',{english:'Penetrate'}),/Duplicate/);assert.throws(()=>model({customWords:{c:{english:'record'}}}),/Duplicate/);});
test('folder rename keeps ID; delete removes only private membership including hidden words',()=>{const m=model();m.setFolder('f',{name:'U6'});m.setWordFolders('w_000001',['f']);m.setFolder('f',{name:'new'});assert.deepEqual(m.getEffectiveWord('w_000001').folderIds,['f']);m.hidePublicWord('w_000001');m.deleteFolder('f');assert.deepEqual(m.getEffectiveWord('w_000001').folderIds,[]);assert.deepEqual(m.getEffectiveWord('w_000001').lessonIds,['U6']);});
test('reset clears all private state and canonical APIs reject old or prototype fields',()=>{const m=model();m.updateWordOverride('w_000001',{meanings:M('mine')});m.hidePublicWord('w_000001');m.setFolder('f',{name:'mine'});m.createCustomWord('c',{english:'custom'});m.setSettings({bgmEnabled:false});m.reset();assert.deepEqual(m.exportState(),{userOverrides:{},customWords:{},hiddenWordIds:[],userFolders:{},settings:{}});for(const key of ['meaning','partOfSpeech','tags','folderId','defaultId','lessonIds'])assert.throws(()=>m.updateWordOverride('w_000001',{[key]:[]}));assert.throws(()=>m.setSettings(JSON.parse('{"__proto__":{"bad":true}}')),/Unsafe/);});
